// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGOzXC_7hNy76w-p2EwWUOONhijpSVDmE',
    appId: '1:983642109584:web:0a040ea630dab5c478ca15',
    messagingSenderId: '983642109584',
    projectId: 'deck-master-1a35a',
    authDomain: 'deck-master-1a35a.firebaseapp.com',
    storageBucket: 'deck-master-1a35a.firebasestorage.app',
    measurementId: 'G-G8D2BJ39EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbL93kLjWHnsvKQ9a0LdvtTKodP3bZG8',
    appId: '1:983642109584:android:5c3e83524aecfa3678ca15',
    messagingSenderId: '983642109584',
    projectId: 'deck-master-1a35a',
    storageBucket: 'deck-master-1a35a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13FBPaMsjm-9ZN72TGfrEg1EtPybOQao',
    appId: '1:983642109584:ios:34b197dc29b651d478ca15',
    messagingSenderId: '983642109584',
    projectId: 'deck-master-1a35a',
    storageBucket: 'deck-master-1a35a.firebasestorage.app',
    iosBundleId: 'com.example.deckMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD13FBPaMsjm-9ZN72TGfrEg1EtPybOQao',
    appId: '1:983642109584:ios:34b197dc29b651d478ca15',
    messagingSenderId: '983642109584',
    projectId: 'deck-master-1a35a',
    storageBucket: 'deck-master-1a35a.firebasestorage.app',
    iosBundleId: 'com.example.deckMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGOzXC_7hNy76w-p2EwWUOONhijpSVDmE',
    appId: '1:983642109584:web:bea1d774c2b34c1778ca15',
    messagingSenderId: '983642109584',
    projectId: 'deck-master-1a35a',
    authDomain: 'deck-master-1a35a.firebaseapp.com',
    storageBucket: 'deck-master-1a35a.firebasestorage.app',
    measurementId: 'G-EZS21Q1SG8',
  );
}
